[[pages]]
name = "Load Dataset"
icon = "âœ…"
is_section = true

[[pages]]
path = "st_tcell/st_dataload.py"
name = "Dataset loading ..."
icon = "ğŸ“¤"

[[pages]]
path = "st_tcell/st_datacombin.py"
name = "Dataset combining ..."
icon = "ğŸ“‘"

[[pages]]
name = "Preprocess"
icon = "âœ…"
is_section = true

[[pages]]
path = "st_tcell/st_preprocess.py"
name = "Data Preprocessing ..."
icon = "ğŸ“"

[[pages]]
path = "st_tcell/st_explor.py"
name = "Data exploring ..."
icon = "ğŸ“Š"

[[pages]]
name = "Train"
icon = "âœ…"
is_section = true

[[pages]]
path = "st_tcell/st_train.py"
name = "Training model ..."
icon = "ğŸ”‚"

[[pages]]
path = "st_tcell/st_distill.py"
name = "Distilling ..."
icon = "ğŸ•"

[[pages]]
name = "Prediction"
icon = "âœ…"
is_section = true

[[pages]]
path = "st_tcell/st_evaluate.py"
name = "evaluate ..."
icon = "â›³"



